language: php
php:
- 5.6
- 7.0
- 7.1
- 7.2
matrix:
  include:
    - php: 7.0
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.1
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.2
      env: COMPOSER_FLAGS="--prefer-lowest"
before_script:
  - composer validate
  - composer self-update
  - composer update --no-interaction ${COMPOSER_FLAGS}
script:
  - vendor/bin/phpunit
cache:
  directories:
  - vendor
  - $HOME/.composer/cache
  - $HOME/.cache/phan-ast/build
  - $HOME/setup
after_success:
    - bash <(curl -s https://codecov.io/bash)