language: php
php:
- 5.6
- 7.0
- 7.1
- 7.2
matrix:
  include:
    - php: 7.0
      env: COMPOSER_FLAGS="--prefer-lowest" PHAN=yes
    - php: 7.1
      env: COMPOSER_FLAGS="--prefer-lowest" PHAN=yes
    - php: 7.2
      env: COMPOSER_FLAGS="--prefer-lowest" PHAN=yes
before_script:
  - if [ "$PHAN" != "" ]; then mkdir setup; curl -L https://raw.githubusercontent.com/phan/phan/master/tests/travis_setup.sh -o setup/travis_setup.sh; bash setup/travis_setup.sh;  fi;
  - if [ "$PHAN" != "" ]; then mkdir /tmp/opcache || true; echo -e 'opcache.enable_cli=1\nopcache.file_cache=/tmp/opcache' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi;
  - if [ "$PHAN" != "" ]; then curl -L https://github.com/phan/phan/releases/download/0.12.0/phan.phar -o phan.phar; fi;
  - composer validate
  - composer self-update
  - composer update --no-interaction ${COMPOSER_FLAGS}
script:
  - vendor/bin/phpunit
  - if [ "$PHAN" != "" ]; then php phan.phar; fi;
cache:
  directories:
  - vendor
  - $HOME/.composer/cache
  - $HOME/.cache/phan-ast/build
  - $HOME/setup
after_success:
    - bash <(curl -s https://codecov.io/bash)